#! /usr/bin/env bash

PRF="${HOME}/.unison/default.prf"

read -p "Enter hostname: " HOST
read -p "Enter space name [swap]: " SPACE
SPACE=${SPACE:-swap}

read -p "Do you want to create service: initd/systemd/[n]? " INITD 
INITD=${INITD:-n}


bash <(curl -s \
"https://raw.githubusercontent.com/pylover/putbox/master/common-install.sh")


mkdir -p $(readlink -f `dirname $PRF`)
echo "# Generated by putbox: client-install.sh
root = ${HOME}
root = ssh://${HOST}
path = ${SPACE} 
repeat = watch
ignore = Name .*.swp
ignore = Name .*.swo
auto = true
batch = true
silent = true
retry = 5
copymax = 2
copyonconflict = true
force = newer
" > ${PRF}


if [[ "${INITD}" == "systemd" ]]; then
  echo "
  [Unit]
  Description=putbox daemon
  After=network.target
  
  [Service]
  User=${USER}
  ExecStart=/usr/local/bin/unison
  RestartSec=2s
  
  [Install]
  WantedBy=multi-user.target
  
  " | sudo tee /etc/systemd/system/putbox.service > /dev/null
  sudo systemctl daemon-reload
  sudo systemctl enable putbox.service
  sudo systemctl start putbox.service

elif [[ "${INITD}" == "initd" ]]; then

  echo "#! /bin/bash

### BEGIN INIT INFO
# Provides:          foo
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: putbox service
# Description:       Run putbox service
### END INIT INFO

# Must be a valid filename
NAME=putbox
PIDFILE=/var/run/\$NAME.pid
#This is the command to be run, give the full pathname
DAEMON=/usr/local/bin/unison

case \"\$1\" in
  start)
    echo -n 'Starting putbox..'
    start-stop-daemon --start --quiet --pidfile \$PIDFILE --chuid ${USER} \
      --exec \$DAEMON
    echo '.'
    ;;
  stop)
    echo -n 'Stopping putbox..'
    start-stop-daemon --stop --quiet --oknodo --pidfile \$PIDFILE
    echo '.'
    ;;
restart)
    echo -n 'Restarting daemon: putbox' 
    start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile \$PIDFILE
    start-stop-daemon --start --quiet --pidfile \$PIDFILE --chuid ${USER} \
      --exec \$DAEMON
    echo "."
	;;
  *)
    echo 'Usage: /etc/init.d/putbox {start|stop|restart}'
    exit 1
    ;;
esac

exit 0
  " | sudo tee /etc/init.d/putbox > /dev/null
  sudo chmod 755 /etc/init.d/putbox
  sudo update-rc.d putbox defaults 
  sudo service putbox start
fi
