#! /usr/bin/env bash

PRF="${HOME}/.unison/default.prf"

read -p "Enter hostname: " HOST
read -p "Enter space name [swap]: " SPACE
SPACE=${SPACE:-swap}

echo $SPACE
echo $HOST

mkdir -p $(readlink -f `dirname $PRF`)
echo "# Generated by putbox: client-install.sh
root = ${HOME}
root = ssh://${HOST}
path = ${SPACE} 
repeat = watch
" > ${PRF}

echo "
[Unit]
Description=putbox daemon
After=network.target

[Service]
User=${USER}
ExecStart=/usr/local/bin/unison
RestartSec=2s

[Install]
WantedBy=multi-user.target

" | sudo tee /etc/systemd/system/putbox.service > /dev/null

sudo systemctl daemon-reload
sudo systemctl enable putbox.service
sudo systemctl start putbox.service


